FROM python:3.11-slim

WORKDIR /app

COPY restock_service /app
COPY shared_data /app/shared_data
COPY api /app/api
COPY requirements.txt ./requirements.txt

ENV PYTHONPATH=/app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
