services:
  db:
    image: postgres:15
    container_name: log430-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stock_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
      
  setup:
    build:
      context: .
      dockerfile: Dockerfile.setup
    depends_on:
      - db
    environment:
      PYTHONPATH: /app
    command: >
      sh -c "sleep 5 &&
             python setup/init_db.py &&
             python setup/seed_db.py"

  stock_service:
    build:
      context: .
      dockerfile: Dockerfile.stock
    depends_on:
      - db
      - redis
    ports:
      - "8001:8000"
    environment:
      PYTHONPATH: /app

  restock_service:
    build:
      context: .
      dockerfile: Dockerfile.restock
    depends_on:
      - db
      - redis
    ports:
      - "8002:8000"
    environment:
      PYTHONPATH: /app

  reporting_service:
    build:
      context: .
      dockerfile: Dockerfile.reporting
    depends_on:
      - db
      - redis
    ports:
      - "8003:8000"
    environment:
      PYTHONPATH: /app
  
  customer_service:
    build:
      context: .
      dockerfile: Dockerfile.customer
    depends_on:
      - db
      - redis
    ports:
      - "8004:8000"
    environment:
      PYTHONPATH: /app

  cart_service:
    build:
      context: .
      dockerfile: Dockerfile.cart
    depends_on:
      - db
      - redis
    ports:
      - "8005:8000"
    environment:
      PYTHONPATH: /app

volumes:
  pgdata:
