@startuml deployment
node "Poste utilisateur" {
  [Console Python]
}
node "Conteneur Docker" {
  folder "App" {
    [main.py] --> [stock_service.py]
    [main.py] --> [reporting_service.py]
    [stock_service.py] --> [product_dao.py]
    [reporting_service.py] --> [product_dao.py]
  }
  database "SQLite produits.db"
}
[product_dao.py] --> [SQLite produits.db]
[Console Python] --> [main.py]
@enduml