@startuml deployment
node "User Terminal" {
  [Console Interface]
}
node "Docker Container" {
  folder "App" {
    [main.py] --> [stock_service.py]
    [stock_service.py] --> [product_dao.py]
  }
  database "SQLite (produits.db)"
}
[stock_service.py] --> [product_dao.py]
[product_dao.py] --> [SQLite (produits.db)]
[Console Interface] --> [main.py]
@enduml
