@startuml implementation
package "presentation_layer" {
  class main.py
  class __init__.py
}

package "service_layer" {
  class stock_service.py
  class __init__.py
}

package "data_access_layer" {
  class product_dao.py
  class init_db.py
  class schema.py
  class __init__.py
  class produits.db
}

package "tests" {
  class test_dao.py
  class test_stock_service.py
  class __init__.py
}

@enduml