@startuml VueCasUtilisation
actor Vendeur
actor Gestionnaire

rectangle "application"{
  usecase "Rechercher produit" as UC1
  usecase "Enregistrer vente" as UC2
  usecase "Annuler vente" as UC3
  usecase "Réapprovisionner" as UC4
  usecase "Générer rapport" as UC5
}
Vendeur --> UC1
Vendeur --> UC2
Vendeur --> UC3
Gestionnaire --> UC4
Gestionnaire --> UC5
@enduml
