@startuml sequence_diagram_annulation
actor User
participant "main.py" as Main
participant "stock_service.py" as Stock
participant "product_dao.py" as DAO

User -> Main : input("Annuler vente")
Main -> Stock : annuler_vente(id, q, magasin_id)
Stock -> DAO : get_by_id(id, magasin_id)
DAO --> Stock : produit
Stock -> DAO : update(nouvelle_quantite)
Main --> User : confirmation
@enduml