@startuml sequence_diagram_vente
actor Utilisateur
participant "main.py" as Main
participant "stock_service.py" as StockService
participant "product_dao.py" as ProduitDAO

Utilisateur -> Main : enregistrer_vente()
Main -> StockService : enregistrer_vente(produit_id, qte, magasin_id)
StockService -> ProduitDAO : get_by_id(produit_id, magasin_id)
ProduitDAO --> StockService : produit
StockService -> ProduitDAO : update(produit)
@enduml