@startuml sequence_diagram_recherche
actor Utilisateur
participant "main.py" as Main
participant "stock_service.py" as StockService
participant "product_dao.py" as ProduitDAO

Utilisateur -> Main : rechercher_produit()
Main -> StockService : rechercher_produit(terme)
StockService -> ProduitDAO : rechercher(terme)
ProduitDAO --> StockService : [produits]
@enduml